### ISSUE TITLE
.murdock: Build apps for different environments.

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#14669]
#### Description
Both https://github.com/RIOT-OS/RIOT/pull/14665 and https://github.com/RIOT-OS/RIOT/pull/14668 showed me once more, that we really should build some tests in their different compile time configurations.

While it is of course really easy to just duplicate the tests for that, I have an idea floating around in my head for some time now, that I don't really have time to execute right now: A descriptive file to define different build environments for Murdock. This optional file could be written in YAML and be structured somewhat like (example would be for the `tests/lwip*` applications):

```yaml
- name: ipv4
  env:
    LWIP_IPV4: 1
- name: ipv6
  env:
    LWIP_IPV6: 1
- name: dualstack
  env:
    LWIP_IPV4: 1
    LWIP_IPV6: 1
```

and be fetched in a [similar manner as boards and toolchains are](https://github.com/RIOT-OS/RIOT/blob/master/.murdock#L148-L168). The name can then be used for the results file to identify the environment (which is why they should be unique).

I think we can also remove a lot of existing code duplication with that approach (see e.g. https://github.com/RIOT-OS/RIOT/issues/6596 by adding `USEMODULE` to that `env` list).

If this would be still possible or make sense with Kconfig, I don't know.
